name: My First Workflow

on:
  push:
    branches:
    - main

  workflow_dispatch:



jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
     - run: echo "Hello World!"
     - name: Checkout
       uses: actions/checkout@v4.2.2
     - name: List files in repository
       run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree 
  job_1:
    runs-on: ubuntu-latest
    steps:
    - run: "echo Job: ${{ github.job }}"
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
    - run: "echo Job: ${{ github.job }}"
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
    - run: "echo Job: ${{ github.job }}"
  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
    - run: "echo Job: ${{ github.job }}"- run: "echo Job: ${{ github.job }}"
